### ISSUE TITLE
Cassandra Source not supporting Double type (Codec not found for requested operation: [double <-> java.lang.Long])

### ISSUE THREAD

**Issue by akumar-nisum-com** [datamountaineer/docs#19]
Environment : Confluent 3.2.0 for zookeper/kafka/Schema Registry / Kafka Rest
                         stream-reactor-0.2.4-3.1.1 for cassandra source and connect.

I have a table structure such as below in cassandra : 

create table kafconnsample.dummy (id int, created timeuuid, listprice float, qty int, price double, PRIMARY KEY (id, created))
WITH CLUSTERING ORDER BY (created asc);
INSERT INTO kafconnsample.dummy (id, created, listprice, qty, price) VALUES (1, now(), 122.7, 150, 94.2);

I have enabled/started cassandra source with following details : 

name=dummy-source
connector.class=com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceConnector
connect.cassandra.key.space=kafconnsample
connect.cassandra.source.kcql=INSERT INTO dummy-topic SELECT * FROM dummy PK created
connect.cassandra.import.mode=incremental
connect.cassandra.contact.points=**.**.**.***
connect.cassandra.username=*****
connect.cassandra.password=*****

Following is the exception : 

 CassandraSourceSetting(com.datamountaineer.connector.config.Config@532599ea,kafconnsample,false,Some(created),60000,CassandraConfigSource({connect.cassandra.import.mode=incremental, connector.class=com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceConnector, connect.cassandra.key.space=kafconnsample, connect.cassandra.contact.points=**.**.**.***, task.class=com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceTask, name=source_dummy, connect.cassandra.source.kcql=INSERT INTO dummy-topic SELECT * FROM dummy PK created, connect.cassandra.password=***********, connect.cassandra.assigned.tables=dummy, connect.cassandra.username=********}),None,ThrowErrorPolicy(),20) (com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader:50)
[2017-03-19 23:41:23,090] INFO Source task WorkerSourceTask{id=source_dummy-0} finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:138)
[2017-03-19 23:41:23,096] INFO Query SELECT * FROM kafconnsample.dummy WHERE created > maxTimeuuid(?) AND created <= minTimeuuid(?)  ALLOW FILTERING executing with bindings (1900-01-01 00:00:00.000Z, 2017-03-19 23:41:23.091Z). (com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader:165)
[2017-03-19 23:41:23,136] INFO Querying returning results for kafconnsample.dummy. (com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader:194)
[2017-03-19 23:41:25,696] INFO 127.0.0.1 - - [20/Mar/2017:06:41:25 +0000] "GET /connectors HTTP/1.1" 200 16  3 (org.apache.kafka.connect.runtime.rest.RestServer:60)
org.apache.kafka.connect.errors.ConnectException: Error processing row Row[1, c614e837-0aa5-11e7-8482-7bd23463f70f, 122.7, 94.2, 150] for table dummy.
	at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader$$anonfun$process$1.applyOrElse(CassandraTableReader.scala:212)
	at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader$$anonfun$process$1.applyOrElse(CassandraTableReader.scala:192)
	at scala.concurrent.Future$$anonfun$onSuccess$1.apply(Future.scala:119)
	at scala.concurrent.Future$$anonfun$onSuccess$1.apply(Future.scala:117)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
**Caused by: com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [double <-> java.lang.Long]**
	at com.datastax.driver.core.CodecRegistry.notFound(CodecRegistry.java:679)
	at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:526)
	at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:506)
	at com.datastax.driver.core.CodecRegistry.access$200(CodecRegistry.java:140)
	at com.datastax.driver.core.CodecRegistry$TypeCodecCacheLoader.load(CodecRegistry.java:211)
	at com.datastax.driver.core.CodecRegistry$TypeCodecCacheLoader.load(CodecRegistry.java:208)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.datastax.driver.core.CodecRegistry.lookupCodec(CodecRegistry.java:480)
	at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:448)
	at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:430)
	at com.datastax.driver.core.AbstractGettableByIndexData.codecFor(AbstractGettableByIndexData.java:69)
	at com.datastax.driver.core.AbstractGettableByIndexData.getLong(AbstractGettableByIndexData.java:152)
	at com.datastax.driver.core.AbstractGettableData.getLong(AbstractGettableData.java:26)
	at com.datastax.driver.core.AbstractGettableData.getLong(AbstractGettableData.java:95)
	at com.datamountaineer.streamreactor.connect.cassandra.utils.CassandraUtils$.mapTypes(CassandraUtils.scala:98)
	at com.datamountaineer.streamreactor.connect.cassandra.utils.CassandraUtils$$anonfun$convert$1.apply(CassandraUtils.scala:74)
	at com.datamountaineer.streamreactor.connect.cassandra.utils.CassandraUtils$$anonfun$convert$1.apply(CassandraUtils.scala:74)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.datamountaineer.streamreactor.connect.cassandra.utils.CassandraUtils$.convert(CassandraUtils.scala:74)
	at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader.com$datamountaineer$streamreactor$connect$cassandra$source$CassandraTableReader$$processRow(CassandraTableReader.scala:236)
	at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader$$anonfun$process$1$$anonfun$1.apply$mcV$sp(CassandraTableReader.scala:207)
	at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader$$anonfun$process$1$$anonfun$1.apply(CassandraTableReader.scala:201)
	at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader$$anonfun$process$1$$anonfun$1.apply(CassandraTableReader.scala:201)
	at scala.util.Try$.apply(Try.scala:192)
	at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader$$anonfun$process$1.applyOrElse(CassandraTableReader.scala:201)
	... 9 more

**Comment by andrewstevenson** [comment]
@akumar-nisum-com Fixed in https://github.com/datamountaineer/stream-reactor/pull/147
