### ISSUE TITLE
ERROR Task MqttSourceConnector...Unable to connect to server (32103)

### ISSUE THREAD

**Issue by vossilius** [datamountaineer/docs#34]
Hi,

I am running a local MQTT cluster (mqtt.muppetnet.lan) of three brokers (192.168.1.2, 192.168.1.118, 192.168.1.25) which I try to connect it to Kafka (Docker image) facing two issues:

**Unable To Connect to Server**

configuraton as per below:
![kafka_ui_1](https://user-images.githubusercontent.com/23253942/32648267-1162aee4-c630-11e7-9abc-201b4ad3a088.jpg)

At first sight the Connector is looking good but no messages are received in the topic. The log shows a connection error:
```
...
[2017-11-10 01:49:45,046] INFO Kafka version : 0.11.0.0-cp1 (org.apache.kafka.common.utils.AppInfoParser:83)
[2017-11-10 01:49:45,047] INFO Kafka commitId : 5cadaa94d0a69e0d (org.apache.kafka.common.utils.AppInfoParser:84)
[2017-11-10 01:49:45,048] INFO 
    ____        __        __  ___                  __        _
   / __ \____ _/ /_____ _/  |/  /___  __  ______  / /_____ _(_)___  ___  ___  _____
  / / / / __ `/ __/ __ `/ /|_/ / __ \/ / / / __ \/ __/ __ `/ / __ \/ _ \/ _ \/ ___/
 / /_/ / /_/ / /_/ /_/ / /  / / /_/ / /_/ / / / / /_/ /_/ / / / / /  __/  __/ /
/_____/\__,_/\__/\__,_/_/  /_/\____/\__,_/_/ /_/\__/\__,_/_/_/ /_/\___/\___/_/
         __  _______  ____________   _____
        /  |/  / __ \/_  __/_  __/  / ___/____  __  _______________
       / /|_/ / / / / / /   / /     \__ \/ __ \/ / / / ___/ ___/ _ \
      / /  / / /_/ / / /   / /     ___/ / /_/ / /_/ / /  / /__/  __/
     /_/  /_/\___\_\/_/   /_/     /____/\____/\__,_/_/   \___/\___/  by Stefan Bocutiu
 v  (com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceTask:41)
[2017-11-10 01:49:45,051] INFO Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:825)
[2017-11-10 01:49:45,054] INFO MqttSourceConfig values: 
	connect.mqtt.clean = true
	connect.mqtt.client.id = kafka_connector_node
	connect.mqtt.converter.throw.on.error = false
	connect.mqtt.error.policy = THROW
	connect.mqtt.hosts = tcp://mqtt.muppetnet.lan:1883
	connect.mqtt.kcql = INSERT INTO test-mqtt SELECT * FROM test
	connect.mqtt.keep.alive = 5000
	connect.mqtt.max.retries = 20
	connect.mqtt.password = [hidden]
	connect.mqtt.retry.interval = 60000
	connect.mqtt.service.quality = 0
	connect.mqtt.ssl.ca.cert = null
	connect.mqtt.ssl.cert = null
	connect.mqtt.ssl.key = null
	connect.mqtt.timeout = 3000
	connect.mqtt.username = node
	connect.progress.enabled = false
 (com.datamountaineer.streamreactor.connect.mqtt.config.MqttSourceConfig:223)
[2017-11-10 01:49:45,055] INFO Creating converter instance for com.datamountaineer.streamreactor.connect.converters.source.BytesConverter (com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceTask:63)
[2017-11-10 01:49:45,055] INFO Starting Mqtt source... (com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceTask:72)
[2017-11-10 01:49:45,056] INFO Connecting to tcp://mqtt.muppetnet.lan:1883 (com.datamountaineer.streamreactor.connect.mqtt.connection.MqttClientConnectionFn$:40)
[2017-11-10 01:49:46,048] INFO 127.0.0.1 - - [10/Nov/2017:01:49:46 +0000] "GET /connectors HTTP/1.1" 200 23  3 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:49:46,059] INFO 127.0.0.1 - - [10/Nov/2017:01:49:46 +0000] "GET /connectors/MqttSourceConnector HTTP/1.1" 200 472  2 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:49:46,074] INFO 127.0.0.1 - - [10/Nov/2017:01:49:46 +0000] "GET /connectors/MqttSourceConnector/status HTTP/1.1" 200 157  1 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:49:52,958] INFO 127.0.0.1 - - [10/Nov/2017:01:49:52 +0000] "GET / HTTP/1.1" 200 54  3 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:49:52,969] INFO 127.0.0.1 - - [10/Nov/2017:01:49:52 +0000] "GET /connectors HTTP/1.1" 200 23  1 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:49:54,040] INFO 127.0.0.1 - - [10/Nov/2017:01:49:54 +0000] "GET /connectors/MqttSourceConnector HTTP/1.1" 200 472  3 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:49:54,061] INFO 127.0.0.1 - - [10/Nov/2017:01:49:54 +0000] "GET /connectors/MqttSourceConnector/status HTTP/1.1" 200 157  9 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:49:54,077] INFO 127.0.0.1 - - [10/Nov/2017:01:49:54 +0000] "GET /connectors/MqttSourceConnector/tasks HTTP/1.1" 200 524  22 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:50:03,775] INFO 127.0.0.1 - - [10/Nov/2017:01:50:03 +0000] "GET / HTTP/1.1" 200 54  8 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:50:03,799] INFO 127.0.0.1 - - [10/Nov/2017:01:50:03 +0000] "GET /connectors HTTP/1.1" 200 23  6 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:50:13,747] INFO 127.0.0.1 - - [10/Nov/2017:01:50:13 +0000] "GET / HTTP/1.1" 200 54  1 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:50:13,759] INFO 127.0.0.1 - - [10/Nov/2017:01:50:13 +0000] "GET /connectors HTTP/1.1" 200 23  3 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:50:23,770] INFO 127.0.0.1 - - [10/Nov/2017:01:50:23 +0000] "GET / HTTP/1.1" 200 54  2 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:50:23,800] INFO 127.0.0.1 - - [10/Nov/2017:01:50:23 +0000] "GET /connectors HTTP/1.1" 200 23  2 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:50:33,771] INFO 127.0.0.1 - - [10/Nov/2017:01:50:33 +0000] "GET / HTTP/1.1" 200 54  1 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:50:33,784] INFO 127.0.0.1 - - [10/Nov/2017:01:50:33 +0000] "GET /connectors HTTP/1.1" 200 23  4 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:50:43,732] INFO 127.0.0.1 - - [10/Nov/2017:01:50:43 +0000] "GET / HTTP/1.1" 200 54  0 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:50:43,743] INFO 127.0.0.1 - - [10/Nov/2017:01:50:43 +0000] "GET /connectors HTTP/1.1" 200 23  1 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:50:53,795] INFO 127.0.0.1 - - [10/Nov/2017:01:50:53 +0000] "GET / HTTP/1.1" 200 54  1 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:50:53,806] INFO 127.0.0.1 - - [10/Nov/2017:01:50:53 +0000] "GET /connectors HTTP/1.1" 200 23  2 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:03,801] INFO 127.0.0.1 - - [10/Nov/2017:01:51:03 +0000] "GET / HTTP/1.1" 200 54  1 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:03,814] INFO 127.0.0.1 - - [10/Nov/2017:01:51:03 +0000] "GET /connectors HTTP/1.1" 200 23  2 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:13,765] INFO 127.0.0.1 - - [10/Nov/2017:01:51:13 +0000] "GET / HTTP/1.1" 200 54  1 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:13,778] INFO 127.0.0.1 - - [10/Nov/2017:01:51:13 +0000] "GET /connectors HTTP/1.1" 200 23  3 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:23,832] INFO 127.0.0.1 - - [10/Nov/2017:01:51:23 +0000] "GET / HTTP/1.1" 200 54  1 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:23,847] INFO 127.0.0.1 - - [10/Nov/2017:01:51:23 +0000] "GET /connectors HTTP/1.1" 200 23  1 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:33,869] INFO 127.0.0.1 - - [10/Nov/2017:01:51:33 +0000] "GET / HTTP/1.1" 200 54  2 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:33,881] INFO 127.0.0.1 - - [10/Nov/2017:01:51:33 +0000] "GET /connectors HTTP/1.1" 200 23  1 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:43,083] INFO 127.0.0.1 - - [10/Nov/2017:01:51:43 +0000] "GET / HTTP/1.1" 200 54  2 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:43,101] INFO 127.0.0.1 - - [10/Nov/2017:01:51:43 +0000] "GET /connectors HTTP/1.1" 200 23  2 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:47,603] INFO 127.0.0.1 - - [10/Nov/2017:01:51:47 +0000] "GET /connectors/MqttSourceConnector HTTP/1.1" 200 472  2 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:47,611] INFO 127.0.0.1 - - [10/Nov/2017:01:51:47 +0000] "GET /connectors HTTP/1.1" 200 23  3 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:47,685] INFO 127.0.0.1 - - [10/Nov/2017:01:51:47 +0000] "GET /connectors/MqttSourceConnector/status HTTP/1.1" 200 157  1 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:47,703] INFO 127.0.0.1 - - [10/Nov/2017:01:51:47 +0000] "GET /connectors/MqttSourceConnector/tasks HTTP/1.1" 200 524  14 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:47,767] INFO 127.0.0.1 - - [10/Nov/2017:01:51:47 +0000] "GET /connectors/MqttSourceConnector HTTP/1.1" 200 472  3 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:48,229] INFO 127.0.0.1 - - [10/Nov/2017:01:51:48 +0000] "GET /connectors/MqttSourceConnector/status HTTP/1.1" 200 157  5 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:51:48,284] INFO 127.0.0.1 - - [10/Nov/2017:01:51:48 +0000] "GET / HTTP/1.1" 200 54  1 (org.apache.kafka.connect.runtime.rest.RestServer:60)
[2017-11-10 01:52:15,817] ERROR Task MqttSourceConnector-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:148)
Unable to connect to server (32103) - java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:94)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:84)
	... 8 more
[2017-11-10 01:52:15,819] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:149)
[2017-11-10 01:52:15,819] INFO Closing the Kafka producer with timeoutMillis = 30000 ms. (org.apache.kafka.clients.producer.KafkaProducer:972)
[2017-11-10 01:52:44,200] INFO 127.0.0.1 - - [10/Nov/2017:01:52:44 +0000] "GET /connectors HTTP/1.1" 200 23  17 (org.apache.kafka.connect.runtime.rest.RestServer:60)
```
The thing is I can connect with another MQTT client to the cluster using the same credentials and successfully publish/subscribe to the topic. Within the Docker image I can ping the the MQTT brokers successfully.

**Kafka UI shows connect/not-connect depending on the broker**

During testing, I noticed that the UI looks good when trying to connect to a broker *which is down*! Yet, the log shows the connection error. Connecting to an active broker, however, results to an error in the UI like below:
![kafka_ui_2](https://user-images.githubusercontent.com/23253942/32648703-0aa5c72e-c632-11e7-8c2a-aa58fb935f53.jpg)

What do I do wrongly?

Tom

**Comment by stheppi** [comment]
Hi @vossilius,
  Do you see anything on the mqtt server logs when the connection is attempted from Kafka connect?  Since you see  a connection refused i would hope there will be some logging on the mqtt server side. Pinging from the docker image is actually login in? (i guess no). 

Have you tried running the connector outside docker in standalonemode?

Stefan

**Comment by vossilius** [comment]
Hi Stephan,
Thanks for your reply!
Well, in verbose mode the MQTT broker (mosquitto) indeed shows connection failed. I can overcome this by setting _allow_anonymous_ to _true_ in the mosquitto.conf bypassing the password credentials. 

Therefore, something does not seem to work right with the authentication. But all my other brokers and nodes authenticate successfully.

Tom

**Comment by andrewstevenson** [comment]
@vossilius can you raise an issue on the stream reactor for the password issue? https://github.com/datamountaineer/stream-reactor

**Comment by stheppi** [comment]
@vossilius,
  Does the MQTT broker say why it rejected the connection or is just flagging it as failed and no other information.

Stefan

**Comment by vossilius** [comment]
@stheppi : As I recall, it was just an ```access denied``` message.
@andrewstevenson : Issue raised [#316](https://github.com/datamountaineer/stream-reactor/issues/316)
Thanks!

**Comment by andrewstevenson** [comment]
closing as issue opened on stream reactor
