### ISSUE TITLE
While inserting records in hbase getting error

### ISSUE THREAD

**Issue by mindfireon812** [datamountaineer/docs#4]
ERROR Task hbase-sink-0 threw an uncaught and unrecoverable exception during shutdown (org.apache.kafka.connect.runtime.WorkerTask:123)
java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
    at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:593)
    at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:577)
    at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:556)
    at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getMetaRegionLocation(ZooKeeperRegistry.java:61)
    at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateMeta(ConnectionManager.java:1211)
    at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1178)
    at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.relocateRegion(ConnectionManager.java:1152)
    at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegionInMeta(ConnectionManager.java:1357)
    at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1181)
    at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:395)
    at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:344)
    at org.apache.hadoop.hbase.client.BufferedMutatorImpl.backgroundFlushCommits(BufferedMutatorImpl.java:238)
    at org.apache.hadoop.hbase.client.BufferedMutatorImpl.flush(BufferedMutatorImpl.java:190)
    at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1430)
    at org.apache.hadoop.hbase.client.HTable.close(HTable.java:1466)
    at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter$$anonfun$close$1.apply(HbaseWriter.scala:111)
    at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter$$anonfun$close$1.apply(HbaseWriter.scala:111)
    at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
    at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter.close(HbaseWriter.scala:111)
    at com.datamountaineer.streamreactor.connect.hbase.HbaseSinkTask$$anonfun$stop$1.apply(HbaseSinkTask.scala:95)
    at com.datamountaineer.streamreactor.connect.hbase.HbaseSinkTask$$anonfun$stop$1.apply(HbaseSinkTask.scala:95)
    at scala.Option.foreach(Option.scala:257)
    at com.datamountaineer.streamreactor.connect.hbase.HbaseSinkTask.stop(HbaseSinkTask.scala:95)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.close(WorkerSinkTask.java:126)
    at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:121)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by mindfireon812** [comment]
I am using Hbase 1.2.3

**Comment by andrewstevenson** [comment]
This a gauca issue. Let check when in the office. Are you using our 2.2 release?

**Comment by andrewstevenson** [comment]
We have a slack channel if you would like to join http://datamountaineer.com/contact/

**Comment by mindfireon812** [comment]
Confluent 3.0.0
HBase 1.2.3
JDK 1.8
kafka - 0.10.0.0

**Comment by andrewstevenson** [comment]
Did you take the hbase jar from https://github.com/datamountaineer/stream-reactor/releases/tag/v0.2.2 ?

**Comment by mindfireon812** [comment]
Built using gradle,will try replacing with this jar
Thanks

**Comment by andrewstevenson** [comment]
there's a clash in the gauva version between hbase and Connect.

**Comment by mindfireon812** [comment]
I will add hbase 1.2.1

**Comment by andrewstevenson** [comment]
I've just tried with HBase 1.2.3 and had no issues. How are you starting Connect?
